### ISSUE TITLE
Update mongodb

### ISSUE THREAD

**Issue by jingsam** [vsivsi/mongotiles#1]
Hi, this repo is awesome. But I get a warning when I install through npm:

```
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
```

It seems that the latest mongodb solve the problem. Could you update it, many thanks~

**Comment by vsivsi** [comment]
Hey, it sounds like you've already done the work... Mind submitting a PR?  I'll try to merge and publish quickly once I see it.

**Comment by vsivsi** [comment]
Merged into master, but need to test with latest versions of everything before releasing.

**Comment by vsivsi** [comment]
Okay, that wasn't too bad.  You should try out the `dev` branch and make sure everything works for you.  When I hear back, I'll push a release to npm.  Enjoy.

**Comment by jingsam** [comment]
Hi, I just implemented another tilelive plugin using mongodb documents to store tiles.
https://github.com/FoxGIS/tilelive-foxgis

**Comment by vsivsi** [comment]
Thanks for the heads up. Not using gridFS is an interesting idea. It will definitely be a bit more efficient.  Does it also support vector tiles?

**Comment by jingsam** [comment]
Yes, It support vector tiles and grids

**Comment by vsivsi** [comment]
Great!  I'm going to go ahead an publish the v0.3 current master to npm, just so there isn't yet another broken package hanging around out there. I'll include a link to your package as well and a blurb about the differences.

**Comment by vsivsi** [comment]
Published
